spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: info
          uri: lb://info
          predicates:
            - Path=/info/**
          filters:
            - StripPrefix=1
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

server:
  port: 8083
  servlet:
    encoding:
      charset: UTF-8
      force: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
