spring:
  application:
    name: info

server:
  port: 8082
  servlet:
    encoding:
      charset: UTF-8
      force: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/